[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testai-sdk"
version = "0.1.0"
description = "A Python SDK for monitoring OpenAI API calls"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Itzhak Guma", email = "your.email@example.com"}
]
dependencies = [
    "openai>=1.0.0",
    "requests>=2.25.0"
]

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest]
testpaths = ["tests"]
